"use client";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { api } from "@/lib/api";

type User = { id:number; username:string; full_name:string; role:string; city?:string };
type Material = { id:number; name:string; quantity:number; unit:string; notes?:string };
type Review = { id:number; source_row:number; task_number?:string; technician_name?:string; exception_type:string; error_message:string; postgres_message?:string; action_taken:string; created_at:string };

export function UsersPanel() { const client=useQueryClient(); const {data=[]}=useQuery({queryKey:["users"],queryFn:()=>api<User[]>("/users")}); const [form,setForm]=useState({full_name:"",username:"",password:"",role:"technician",city:""}); const [error,setError]=useState(""); async function submit(e:React.FormEvent){e.preventDefault();setError("");try{await api("/users",{method:"POST",body:JSON.stringify(form)});setForm({full_name:"",username:"",password:"",role:"technician",city:""});client.invalidateQueries({queryKey:["users"]});}catch{setError("تعذر إضافة المستخدم. تحقق من الصلاحية والبيانات.");}} return <div className="grid gap-5 xl:grid-cols-[1fr_1.4fr]"><form onSubmit={submit} className="panel"><h2 className="font-bold">إضافة مستخدم</h2><div className="mt-4 grid gap-3"><input required placeholder="الاسم الكامل" value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})} className="rounded-xl border bg-transparent p-3"/><input required placeholder="اسم المستخدم" value={form.username} onChange={e=>setForm({...form,username:e.target.value})} className="rounded-xl border bg-transparent p-3"/><input required minLength={10} type="password" placeholder="كلمة المرور (10 أحرف على الأقل)" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} className="rounded-xl border bg-transparent p-3"/><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})} className="rounded-xl border bg-transparent p-3"><option value="technician">فني</option><option value="manager">مدير</option><option value="admin">مسؤول</option></select><input placeholder="المدينة" value={form.city} onChange={e=>setForm({...form,city:e.target.value})} className="rounded-xl border bg-transparent p-3"/></div>{error&&<p className="mt-3 text-sm text-red-600">{error}</p>}<button className="mt-4 w-full rounded-xl bg-brand p-3 font-semibold text-white">إضافة</button></form><div className="panel overflow-x-auto"><h2 className="mb-4 font-bold">المستخدمون</h2><table className="w-full text-right text-sm"><thead><tr className="text-slate-500"><th>الاسم</th><th>المستخدم</th><th>الدور</th><th>المدينة</th></tr></thead><tbody>{data.map(user=><tr className="border-t" key={user.id}><td className="py-3">{user.full_name}</td><td>{user.username}</td><td>{user.role}</td><td>{user.city||"—"}</td></tr>)}</tbody></table></div></div>; }

export function MaterialsPanel() { const client=useQueryClient(); const {data=[]}=useQuery({queryKey:["materials"],queryFn:()=>api<Material[]>("/materials")}); const [form,setForm]=useState({name:"",quantity:0,unit:"قطعة",notes:""}); async function add(e:React.FormEvent){e.preventDefault();await api("/materials",{method:"POST",body:JSON.stringify(form)});setForm({name:"",quantity:0,unit:"قطعة",notes:""});client.invalidateQueries({queryKey:["materials"]});} async function adjust(id:number,delta:number){await api(`/materials/${id}/quantity?delta=${delta}`,{method:"PATCH"});client.invalidateQueries({queryKey:["materials"]});} return <div className="grid gap-5 xl:grid-cols-[1fr_1.4fr]"><form onSubmit={add} className="panel"><h2 className="font-bold">إضافة مادة</h2><div className="mt-4 grid gap-3"><input required placeholder="اسم المادة" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="rounded-xl border bg-transparent p-3"/><input required min="0" type="number" value={form.quantity} onChange={e=>setForm({...form,quantity:+e.target.value})} className="rounded-xl border bg-transparent p-3"/><input required placeholder="الوحدة" value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})} className="rounded-xl border bg-transparent p-3"/><textarea placeholder="ملاحظات" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} className="rounded-xl border bg-transparent p-3"/></div><button className="mt-4 w-full rounded-xl bg-brand p-3 font-semibold text-white">حفظ المادة</button></form><div className="panel overflow-x-auto"><h2 className="mb-4 font-bold">المخزون</h2><table className="w-full text-right text-sm"><thead><tr className="text-slate-500"><th>المادة</th><th>الكمية</th><th>الوحدة</th><th>إجراء</th></tr></thead><tbody>{data.map(item=><tr className="border-t" key={item.id}><td className="py-3">{item.name}</td><td>{item.quantity}</td><td>{item.unit}</td><td className="space-x-2 space-x-reverse"><button onClick={()=>adjust(item.id,1)} className="rounded bg-emerald-100 px-2 py-1 text-emerald-700">+1</button><button onClick={()=>adjust(item.id,-1)} className="rounded bg-red-100 px-2 py-1 text-red-700">-1</button></td></tr>)}</tbody></table></div></div>; }

export function ImportReviewPanel() { const client=useQueryClient(); const {data}=useQuery({queryKey:["import-reviews"],queryFn:()=>api<{items:Review[]}>("/import-reviews")}); async function ignore(id:number){await api(`/import-reviews/${id}/ignore`,{method:"POST"});client.invalidateQueries({queryKey:["import-reviews"]});} return <div className="panel overflow-x-auto"><h2 className="mb-2 font-bold">مراجعة الاستيراد</h2><p className="mb-4 text-sm text-slate-500">لا تظهر تفاصيل الخطأ الخام للمستخدم النهائي خارج هذا القسم المخصص.</p><table className="w-full text-right text-sm"><thead><tr className="text-slate-500"><th>الصف</th><th>المهمة</th><th>الفني</th><th>السبب</th><th>الإجراء</th><th></th></tr></thead><tbody>{data?.items.map(row=><tr className="border-t" key={row.id}><td className="py-3">{row.source_row}</td><td>{row.task_number||"—"}</td><td>{row.technician_name||"—"}</td><td title={row.error_message}>{row.exception_type}</td><td>{row.action_taken}</td><td><button onClick={()=>ignore(row.id)} className="rounded-lg bg-slate-100 px-2 py-1 text-xs dark:bg-slate-800">تجاهل</button></td></tr>)}</tbody></table></div>; }
