"use client";

import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { api } from "@/lib/api";

type User = { id: number; username: string; full_name: string; role: "admin" | "technician"; city?: string };
type Material = { id: number; name: string; quantity: number; unit: string; notes?: string };
type Review = { id: number; source_row: number; task_number?: string; technician_name?: string; subscription_number?: string; task_type?: string; exception_type: string; error_message: string; postgres_message?: string; action_taken: string; created_at: string };

const roleLabel = (role: User["role"]) => role === "admin" ? "مدير" : "فني";

export function UsersPanel({ mode = "all" }: { mode?: "all" | "list" | "create" | "edit" | "deactivate" }) {
  const client = useQueryClient();
  const { data = [], isLoading, isError } = useQuery({ queryKey: ["users"], queryFn: () => api<User[]>("/users") });
  const [form, setForm] = useState({ full_name: "", username: "", password: "", role: "technician" as User["role"], city: "" });
  const [editing, setEditing] = useState<User>(); const [busyUser, setBusyUser] = useState<number>();
  const [message, setMessage] = useState("");
  const refresh = () => client.invalidateQueries({ queryKey: ["users"] });
  async function submit(event: React.FormEvent) { event.preventDefault(); setMessage(""); try { await api("/users", { method: "POST", body: JSON.stringify(form) }); setForm({ full_name: "", username: "", password: "", role: "technician", city: "" }); setMessage("تمت إضافة المستخدم."); refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "تعذر إضافة المستخدم."); } }
  async function update(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!editing) return; try { await api(`/users/${editing.id}`, { method: "PATCH", body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); setEditing(undefined); setMessage("تم حفظ بيانات المستخدم."); refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "تعذر تعديل المستخدم."); } }
  async function deactivate(user: User) { if (!window.confirm(`تعطيل المستخدم ${user.full_name}؟`)) return; setBusyUser(user.id); setMessage("جارٍ تعطيل المستخدم…"); try { await api(`/users/${user.id}`, { method: "DELETE" }); setMessage("تم تعطيل الحساب مع الحفاظ على السجل التاريخي."); refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "تعذر تعطيل المستخدم."); } finally { setBusyUser(undefined); } }
  const showCreate = mode === "all" || mode === "create";
  const showTable = mode !== "create";
  return <div className={showCreate && showTable ? "grid gap-5 xl:grid-cols-[1fr_1.4fr]" : "space-y-5"}>
    {showCreate && <form onSubmit={submit} className="panel"><h2 className="font-bold">إضافة مستخدم</h2><div className="mt-4 grid gap-3"><input required placeholder="الاسم الكامل" value={form.full_name} onChange={e => setForm({ ...form, full_name: e.target.value })} className="rounded-xl border bg-transparent p-3" /><input required placeholder="اسم المستخدم" value={form.username} onChange={e => setForm({ ...form, username: e.target.value })} className="rounded-xl border bg-transparent p-3" /><input required minLength={10} type="password" placeholder="كلمة المرور (10 أحرف على الأقل)" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} className="rounded-xl border bg-transparent p-3" /><select value={form.role} onChange={e => setForm({ ...form, role: e.target.value as User["role"] })} className="rounded-xl border bg-transparent p-3"><option value="technician">فني</option><option value="admin">مدير</option></select><input placeholder="المدينة" value={form.city} onChange={e => setForm({ ...form, city: e.target.value })} className="rounded-xl border bg-transparent p-3" /></div><button className="mt-4 w-full rounded-xl bg-brand p-3 font-semibold text-white">إضافة</button>{message && <p className="mt-3 text-sm text-slate-500">{message}</p>}</form>}
    {showTable && <div className="panel overflow-x-auto"><h2 className="mb-4 font-bold">{mode === "edit" ? "تعديل المستخدمين" : mode === "deactivate" ? "تعطيل المستخدمين" : "المستخدمون"}</h2>{message && <p className="mb-3 rounded-lg bg-slate-100 p-3 text-sm dark:bg-slate-800">{message}</p>}{isLoading && <p className="py-5 text-sm text-slate-500">جارٍ تحميل المستخدمين…</p>}{isError && <p className="py-5 text-sm text-red-600">تعذر تحميل المستخدمين. تأكد من اتصال API وصلاحيات المدير.</p>}{editing && <form onSubmit={update} className="mb-4 grid gap-2 rounded-xl border p-3 sm:grid-cols-2"><input name="full_name" required defaultValue={editing.full_name} className="rounded border bg-transparent p-2" /><select name="role" defaultValue={editing.role} className="rounded border bg-transparent p-2"><option value="technician">فني</option><option value="admin">مدير</option></select><input name="city" defaultValue={editing.city} placeholder="المدينة" className="rounded border bg-transparent p-2" /><div className="flex gap-2"><button className="rounded bg-brand px-3 py-2 text-sm text-white">حفظ</button><button type="button" onClick={() => setEditing(undefined)} className="px-2 text-sm">إلغاء</button></div></form>}{!isLoading && !isError && <table className="w-full text-right text-sm"><thead><tr className="text-slate-500"><th>الاسم</th><th>المستخدم</th><th>الدور</th><th>المدينة</th>{mode !== "list" && <th>الإجراء</th>}</tr></thead><tbody>{data.map(user => <tr className="border-t" key={user.id}><td className="py-3">{user.full_name}</td><td>{user.username}</td><td>{roleLabel(user.role)}</td><td>{user.city || "—"}</td>{mode !== "list" && <td className="space-x-2 space-x-reverse">{mode !== "deactivate" && <button onClick={() => setEditing(user)} className="text-xs text-brand">تعديل</button>}{mode !== "edit" && <button onClick={() => deactivate(user)} className="text-xs text-red-600">تعطيل</button>}</td>}</tr>)}</tbody></table>}</div>}
  </div>;
}

export function MaterialsPanel() {
  const client = useQueryClient(); const { data = [] } = useQuery({ queryKey: ["materials"], queryFn: () => api<Material[]>("/materials") });
  const [form, setForm] = useState({ name: "", quantity: 0, unit: "قطعة", notes: "" });
  const refresh = () => client.invalidateQueries({ queryKey: ["materials"] });
  return <div className="grid gap-5 xl:grid-cols-[1fr_1.4fr]"><form onSubmit={async e => { e.preventDefault(); await api("/materials", { method: "POST", body: JSON.stringify(form) }); setForm({ name: "", quantity: 0, unit: "قطعة", notes: "" }); refresh(); }} className="panel"><h2 className="font-bold">إضافة مادة</h2><div className="mt-4 grid gap-3"><input required placeholder="اسم المادة" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} className="rounded-xl border bg-transparent p-3" /><input required min="0" type="number" value={form.quantity} onChange={e => setForm({ ...form, quantity: +e.target.value })} className="rounded-xl border bg-transparent p-3" /><input required placeholder="الوحدة" value={form.unit} onChange={e => setForm({ ...form, unit: e.target.value })} className="rounded-xl border bg-transparent p-3" /><textarea placeholder="ملاحظات" value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })} className="rounded-xl border bg-transparent p-3" /></div><button className="mt-4 w-full rounded-xl bg-brand p-3 font-semibold text-white">حفظ المادة</button></form><div className="panel overflow-x-auto"><h2 className="mb-4 font-bold">المخزون</h2><table className="w-full text-right text-sm"><thead><tr className="text-slate-500"><th>المادة</th><th>الكمية</th><th>الوحدة</th><th>إجراء</th></tr></thead><tbody>{data.map(item => <tr className="border-t" key={item.id}><td className="py-3">{item.name}</td><td>{item.quantity}</td><td>{item.unit}</td><td className="space-x-2 space-x-reverse"><button onClick={async () => { await api(`/materials/${item.id}/quantity?delta=1`, { method: "PATCH" }); refresh(); }} className="rounded bg-emerald-100 px-2 py-1 text-emerald-700">+1</button><button onClick={async () => { await api(`/materials/${item.id}/quantity?delta=-1`, { method: "PATCH" }); refresh(); }} className="rounded bg-red-100 px-2 py-1 text-red-700">-1</button></td></tr>)}</tbody></table></div></div>;
}

export function ImportReviewPanel() {
  const client = useQueryClient(); const { data } = useQuery({ queryKey: ["import-reviews"], queryFn: () => api<{ items: Review[] }>("/import-reviews") });
  const [editing, setEditing] = useState<Review>(); const [message, setMessage] = useState(""); const refresh = () => client.invalidateQueries({ queryKey: ["import-reviews"] });
  async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!editing) return; const retry = (event.nativeEvent as SubmitEvent).submitter?.getAttribute("name") === "reinsert"; const payload = Object.fromEntries([...new FormData(event.currentTarget).entries()].filter(([key, value]) => key !== "reinsert" && value !== "")); try { if (retry) { const result = await api<{ ok: boolean; message?: string }>(`/import-reviews/${editing.id}/reinsert`, { method: "POST", body: JSON.stringify(payload) }); setMessage(result.ok ? "تمت إعادة إدراج المهمة بنجاح." : result.message ?? "بقي السجل في المراجعة."); if (result.ok) setEditing(undefined); } else { await api(`/import-reviews/${editing.id}`, { method: "PATCH", body: JSON.stringify(payload) }); setMessage("تم حفظ التصحيح. يمكنك الآن إعادة الإدراج."); } refresh(); } catch { setMessage("تعذر تنفيذ الإجراء. بقي السجل آمناً في المراجعة."); } }
  return <div className="panel overflow-x-auto"><h2 className="mb-2 font-bold">مراجعة الاستيراد</h2><p className="mb-4 text-sm text-slate-500">لا تظهر تفاصيل الخطأ الخام للمستخدم النهائي خارج هذا القسم المخصص.</p>{message && <p className="mb-4 rounded-lg bg-slate-100 p-3 text-sm dark:bg-slate-800">{message}</p>}{editing && <form onSubmit={save} className="mb-5 grid gap-3 rounded-xl border border-brand/30 bg-brand/5 p-4 sm:grid-cols-2"><input name="task_number" required defaultValue={editing.task_number} placeholder="رقم المهمة" className="rounded-lg border bg-transparent p-2" /><input name="technician_name" defaultValue={editing.technician_name} placeholder="الفني" className="rounded-lg border bg-transparent p-2" /><input name="subscription_number" defaultValue={editing.subscription_number} placeholder="رقم الاشتراك" className="rounded-lg border bg-transparent p-2" /><input name="task_type" defaultValue={editing.task_type} placeholder="نوع المهمة" className="rounded-lg border bg-transparent p-2" /><div className="flex gap-2 sm:col-span-2"><button className="rounded-lg bg-brand px-3 py-2 text-sm font-semibold text-white">حفظ الإصلاح</button><button name="reinsert" className="rounded-lg bg-emerald-600 px-3 py-2 text-sm font-semibold text-white">إعادة الإدراج</button><button type="button" onClick={() => setEditing(undefined)} className="rounded-lg px-3 py-2 text-sm">إلغاء</button></div></form>}<table className="w-full text-right text-sm"><thead><tr className="text-slate-500"><th>الصف</th><th>المهمة</th><th>الفني</th><th>الاشتراك</th><th>النوع</th><th>السبب</th><th>PostgreSQL</th><th>الإجراء</th><th /></tr></thead><tbody>{data?.items.map(row => <tr className="border-t" key={row.id}><td className="py-3">{row.source_row}</td><td>{row.task_number || "—"}</td><td>{row.technician_name || "—"}</td><td>{row.subscription_number || "—"}</td><td>{row.task_type || "—"}</td><td title={row.error_message}>{row.exception_type}</td><td title={row.postgres_message}>{row.postgres_message ? "متاح" : "—"}</td><td>{row.action_taken}</td><td className="space-x-2 space-x-reverse"><button onClick={() => setEditing(row)} className="rounded-lg bg-indigo-100 px-2 py-1 text-xs text-indigo-700 dark:bg-indigo-950 dark:text-indigo-300">إصلاح</button><button onClick={async () => { await api(`/import-reviews/${row.id}/ignore`, { method: "POST" }); refresh(); }} className="rounded-lg bg-slate-100 px-2 py-1 text-xs dark:bg-slate-800">تجاهل</button></td></tr>)}</tbody></table></div>;
}
