"use client";
import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { api, apiBase } from "@/lib/api";
import { authHeaders } from "@/lib/auth";
type DailyReport = { id: number; technician_id: number; report_date: string; image_mime: string; created_at: string };
export function ReportUpload() {
  const client = useQueryClient(); const { data = [] } = useQuery({ queryKey: ["daily-reports"], queryFn: () => api<DailyReport[]>("/daily-reports") });
  const [file, setFile] = useState<File>(); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [busy, setBusy] = useState(""); const [result, setResult] = useState("");
  async function upload() { if (!file || busy) return; if (file.size > 25 * 1024 * 1024) { setResult("حجم الصورة يجب ألا يتجاوز 25 ميجابايت."); return; } setBusy("save"); setResult("جارٍ حفظ التقرير…"); try { const body = new FormData(); body.append("image", file); await api(`/daily-reports?report_date=${encodeURIComponent(date)}`, { method: "POST", body }); setResult("تم حفظ التقرير بنجاح."); setFile(undefined); client.invalidateQueries({ queryKey: ["daily-reports"] }); } catch (error) { setResult(error instanceof Error ? error.message : "تعذر حفظ التقرير."); } finally { setBusy(""); } }
  async function view(report: DailyReport) { setBusy(`view-${report.id}`); try { const response = await fetch(`${apiBase}/daily-reports/${report.id}/image`, { headers: authHeaders() }); if (!response.ok) throw new Error("تعذر عرض التقرير."); const url = URL.createObjectURL(await response.blob()); window.open(url, "_blank", "noopener,noreferrer"); window.setTimeout(() => URL.revokeObjectURL(url), 60000); } catch (error) { setResult(error instanceof Error ? error.message : "تعذر عرض التقرير."); } finally { setBusy(""); } }
  async function remove(report: DailyReport) { if (!window.confirm("حذف هذا التقرير؟")) return; setBusy(`delete-${report.id}`); try { await api(`/daily-reports/${report.id}`, { method: "DELETE" }); setResult("تم حذف التقرير."); client.invalidateQueries({ queryKey: ["daily-reports"] }); } catch (error) { setResult(error instanceof Error ? error.message : "تعذر حذف التقرير."); } finally { setBusy(""); } }
  return <section className="panel max-w-4xl"><h2 className="font-bold">التقارير اليومية</h2><p className="mt-1 text-sm text-slate-500">احفظ تقريرًا جديدًا أو اعرض واحذف التقارير السابقة.</p><div className="mt-5 flex flex-wrap items-end gap-3"><label className="grid gap-1 text-sm">التاريخ<input type="date" value={date} onChange={e => setDate(e.target.value)} className="rounded-xl border bg-transparent p-3" /></label><label className="grid min-w-64 gap-1 text-sm">الصورة<input type="file" accept="image/jpeg,image/png" onChange={e => setFile(e.target.files?.[0])} className="rounded-xl border bg-transparent p-3" /></label><button type="button" onClick={upload} disabled={!file || Boolean(busy)} className="flex items-center gap-2 rounded-xl bg-brand px-5 py-3 font-semibold text-white disabled:opacity-50">{busy === "save" && <span className="size-4 animate-spin rounded-full border-2 border-white/40 border-t-white" />}{busy === "save" ? "جارٍ الحفظ…" : "حفظ التقرير"}</button></div>{result && <p className="mt-3 text-sm text-slate-600 dark:text-slate-300">{result}</p>}<div className="mt-6 overflow-x-auto"><table className="w-full text-right text-sm"><thead><tr className="text-slate-500"><th className="py-2">التاريخ</th><th>النوع</th><th>وقت الرفع</th><th>الإجراءات</th></tr></thead><tbody>{data.map(report => <tr key={report.id} className="border-t"><td className="py-3">{report.report_date}</td><td>{report.image_mime}</td><td>{new Date(report.created_at).toLocaleString("ar-SA")}</td><td className="flex gap-2"><button type="button" disabled={Boolean(busy)} onClick={() => view(report)} className="rounded-lg bg-indigo-100 px-3 py-1.5 text-xs text-indigo-700 disabled:opacity-50">{busy === `view-${report.id}` ? "جارٍ العرض…" : "عرض التقرير"}</button><button type="button" disabled={Boolean(busy)} onClick={() => remove(report)} className="rounded-lg bg-red-100 px-3 py-1.5 text-xs text-red-700 disabled:opacity-50">{busy === `delete-${report.id}` ? "جارٍ الحذف…" : "حذف التقرير"}</button></td></tr>)}</tbody></table>{!data.length && <p className="py-6 text-center text-sm text-slate-500">لا توجد تقارير محفوظة.</p>}</div></section>;
}
