"use client";

import { useQueryClient } from "@tanstack/react-query";
import { MapPin, Mic, MicOff } from "lucide-react";
import { useRef, useState } from "react";
import { api } from "@/lib/api";
import { queueTask } from "@/lib/offline-queue";

type Form = { task_number: string; subscription_number: string; task_type: string; task_status: string; notes: string; customer_name: string; customer_phone: string; due_at: string; latitude: string; longitude: string };
const initial: Form = { task_number: "", subscription_number: "", task_type: "تقني", task_status: "تم الفحص", notes: "", customer_name: "", customer_phone: "", due_at: "", latitude: "", longitude: "" };

type Recognition = { lang: string; interimResults: boolean; continuous: boolean; start: () => void; stop: () => void; onresult: ((event: { results: ArrayLike<ArrayLike<{ transcript: string }>> }) => void) | null; onend: (() => void) | null; onerror: (() => void) | null };
type RecognitionWindow = Window & { SpeechRecognition?: new () => Recognition; webkitSpeechRecognition?: new () => Recognition };

export function TaskCreateForm() {
  const client = useQueryClient(); const [form, setForm] = useState(initial); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [listening, setListening] = useState(false); const recognition = useRef<Recognition | undefined>(undefined);
  const update = (key: keyof Form, value: string) => setForm(current => ({ ...current, [key]: value }));
  function voice() { if (listening) { recognition.current?.stop(); setListening(false); return; } const Constructor = (window as RecognitionWindow).SpeechRecognition ?? (window as RecognitionWindow).webkitSpeechRecognition; if (!Constructor) { setMessage("الإملاء الصوتي غير مدعوم في هذا المتصفح."); return; } const instance = new Constructor(); instance.lang = "ar-SA"; instance.interimResults = false; instance.continuous = false; instance.onresult = event => update("notes", `${form.notes}${form.notes ? " " : ""}${Array.from(event.results).map(result => result[0].transcript).join(" ")}`); instance.onend = () => setListening(false); instance.onerror = () => setListening(false); recognition.current = instance; instance.start(); setListening(true); }
  function locate() { if (!navigator.geolocation) { setMessage("الموقع غير مدعوم في هذا الجهاز."); return; } navigator.geolocation.getCurrentPosition(position => { update("latitude", String(position.coords.latitude)); update("longitude", String(position.coords.longitude)); setMessage("تم تحديد موقع المهمة."); }, () => setMessage("تعذر تحديد الموقع. تحقق من صلاحية الموقع."), { enableHighAccuracy: true, timeout: 8000, maximumAge: 60_000 }); }
  async function submit(event: React.FormEvent) { event.preventDefault(); if (busy) return; setBusy(true); setMessage(""); const idempotencyKey = crypto.randomUUID(); const payload = { ...form, due_at: form.due_at ? new Date(form.due_at).toISOString() : null, latitude: form.latitude ? Number(form.latitude) : null, longitude: form.longitude ? Number(form.longitude) : null }; try { await api("/tasks", { method: "POST", headers: { "Idempotency-Key": idempotencyKey }, body: JSON.stringify(payload) }); setMessage("تمت إضافة المهمة باسمك وفي مدينتك."); setForm(initial); client.invalidateQueries({ queryKey: ["tasks"] }); } catch (error) { if (!navigator.onLine || error instanceof TypeError) { queueTask(payload as unknown as Record<string, string>, idempotencyKey); setMessage("لا يوجد اتصال. تم حفظ المهمة وستتم مزامنتها تلقائيًا."); setForm(initial); } else setMessage(error instanceof Error ? error.message : "تعذر إضافة المهمة."); } finally { setBusy(false); } }
  return <form onSubmit={submit} className="panel max-w-3xl"><h2 className="font-bold">تسجيل مهمة جديدة</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><input required placeholder="رقم المهمة" value={form.task_number} onChange={e => update("task_number", e.target.value)} className="rounded-xl border bg-transparent p-3"/><input placeholder="رقم الاشتراك" value={form.subscription_number} onChange={e => update("subscription_number", e.target.value)} className="rounded-xl border bg-transparent p-3"/><select value={form.task_type} onChange={e => update("task_type", e.target.value)} className="rounded-xl border bg-transparent p-3"><option>تقني</option><option>زيرا</option></select><select value={form.task_status} onChange={e => update("task_status", e.target.value)} className="rounded-xl border bg-transparent p-3"><option>تم الفحص</option><option>عائق</option><option>مزال</option></select><input placeholder="اسم العميل" value={form.customer_name} onChange={e => update("customer_name", e.target.value)} className="rounded-xl border bg-transparent p-3"/><input placeholder="جوال العميل" value={form.customer_phone} onChange={e => update("customer_phone", e.target.value)} className="rounded-xl border bg-transparent p-3"/><label className="grid gap-1 text-sm text-slate-500">موعد SLA<input type="datetime-local" value={form.due_at} onChange={e => update("due_at", e.target.value)} className="rounded-xl border bg-transparent p-3 text-slate-900 dark:text-slate-100"/></label><div className="flex items-end gap-2"><input placeholder="ملاحظات" value={form.notes} onChange={e => update("notes", e.target.value)} className="min-w-0 flex-1 rounded-xl border bg-transparent p-3"/><button type="button" onClick={voice} className={`rounded-xl border p-3 ${listening ? "text-red-600" : ""}`} title="إملاء صوتي بالعربية" aria-label="إملاء صوتي">{listening ? <MicOff size={18}/> : <Mic size={18}/>}</button></div><div className="flex items-end gap-2 sm:col-span-2"><input placeholder="خط العرض" value={form.latitude} onChange={e => update("latitude", e.target.value)} className="min-w-0 flex-1 rounded-xl border bg-transparent p-3"/><input placeholder="خط الطول" value={form.longitude} onChange={e => update("longitude", e.target.value)} className="min-w-0 flex-1 rounded-xl border bg-transparent p-3"/><button type="button" onClick={locate} className="rounded-xl border p-3" title="تحديد الموقع الحالي" aria-label="تحديد الموقع"><MapPin size={18}/></button></div></div><button disabled={busy} className="mt-4 flex items-center gap-2 rounded-xl bg-brand px-5 py-3 font-semibold text-white disabled:opacity-60">{busy ? "جارٍ الحفظ…" : "إضافة المهمة"}</button>{message && <p className="mt-3 text-sm text-slate-500">{message}</p>}</form>;
}
