"use client";

import { useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "@/lib/api";

type Task = { id: number; task_number: string; technician_name: string; subscription_number: string; task_type: string; task_status: string; city?: string; execution_date: string };
type TaskPage = { items: Task[]; total: number; page: number; page_size: number };

export function TaskManagementTable() {
  const client = useQueryClient(); const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const [selected, setSelected] = useState<number[]>([]); const [message, setMessage] = useState("");
  const { data, isLoading, isError } = useQuery({ queryKey: ["tasks", page, search], queryFn: () => api<TaskPage>(`/tasks?page=${page}&page_size=25&search=${encodeURIComponent(search)}`) });
  const pages = Math.max(1, Math.ceil((data?.total ?? 0) / 25)); const rows = data?.items ?? []; const allSelected = rows.length > 0 && rows.every(row => selected.includes(row.id));
  const visible = useMemo(() => rows, [rows]);
  function toggle(id: number) { setSelected(current => current.includes(id) ? current.filter(value => value !== id) : [...current, id]); }
  function toggleAll() { setSelected(allSelected ? [] : visible.map(row => row.id)); }
  async function deleteSelected() { if (!selected.length || !window.confirm(`حذف ${selected.length} مهمة محددة؟`)) return; try { await api(`/tasks?${selected.map(id => `task_ids=${id}`).join("&")}`, { method: "DELETE" }); setSelected([]); setMessage("تم حذف المهام المحددة."); client.invalidateQueries({ queryKey: ["tasks"] }); } catch (error) { setMessage(error instanceof Error ? error.message : "تعذر حذف المهام."); } }
  async function deleteAll() { if (!data?.total || !window.confirm(`حذف جميع المهام وعددها ${data.total}؟ لا يمكن التراجع.`)) return; try { await api("/tasks?delete_all=true", { method: "DELETE" }); setSelected([]); setMessage("تم حذف جميع المهام."); client.invalidateQueries({ queryKey: ["tasks"] }); } catch (error) { setMessage(error instanceof Error ? error.message : "تعذر حذف جميع المهام."); } }
  return <section className="panel overflow-x-auto"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-xl font-bold">المهام</h1><p className="text-sm text-slate-500">عرض المهام وإدارتها حسب المدينة والفني.</p></div><input value={search} onChange={event => { setSearch(event.target.value); setPage(1); }} placeholder="ابحث عن مهمة…" className="rounded-xl border bg-transparent px-3 py-2 text-sm" /></div>{message && <p className="mb-4 rounded-lg bg-slate-100 p-3 text-sm dark:bg-slate-800">{message}</p>}<div className="mb-4 flex flex-wrap gap-2"><button type="button" disabled={!selected.length} onClick={deleteSelected} className="rounded-xl bg-red-600 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">حذف المحدد ({selected.length})</button><button type="button" disabled={!data?.total} onClick={deleteAll} className="rounded-xl border border-red-300 px-3 py-2 text-sm text-red-600 disabled:opacity-50">حذف الكل</button></div>{isError && <p className="py-5 text-sm text-red-600">تعذر تحميل المهام.</p>}{!isError && <table className="w-full text-right text-sm"><thead><tr className="text-slate-500"><th className="px-3 py-3"><input type="checkbox" checked={allSelected} onChange={toggleAll} aria-label="تحديد كل مهام الصفحة" /></th><th>رقم المهمة</th><th>الفني</th><th>الاشتراك</th><th>النوع</th><th>الحالة</th><th>المدينة</th><th>التاريخ</th></tr></thead><tbody>{rows.map(row => <tr className="border-t" key={row.id}><td className="px-3 py-3"><input type="checkbox" checked={selected.includes(row.id)} onChange={() => toggle(row.id)} aria-label={`تحديد ${row.task_number}`} /></td><td>{row.task_number}</td><td>{row.technician_name}</td><td>{row.subscription_number}</td><td>{row.task_type}</td><td>{row.task_status}</td><td>{row.city || "—"}</td><td>{row.execution_date}</td></tr>)}</tbody></table>}{isLoading && <p className="p-5 text-sm text-slate-500">جارٍ التحميل…</p>}{!isLoading && !isError && !rows.length && <p className="p-8 text-center text-sm">لا توجد مهام.</p>}<div className="mt-4 flex items-center justify-between border-t pt-4 text-sm"><span>{data?.total ?? 0} مهمة</span><div className="flex items-center gap-2"><button type="button" disabled={page <= 1 || isLoading} onClick={() => setPage(value => value - 1)} className="rounded border px-3 py-1 disabled:opacity-50">السابق</button><span>{page} / {pages}</span><button type="button" disabled={page >= pages || isLoading} onClick={() => setPage(value => value + 1)} className="rounded border px-3 py-1 disabled:opacity-50">التالي</button></div></div></section>;
}
