"use client";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { api } from "@/lib/api";
import { authHeaders } from "@/lib/auth";

type Assignment={id:number;task_number:string;subscription_number:string;task_type:string;task_status:string;assigned_date:string;notes?:string};
type Technician={id:number;full_name:string;role:string};
type DailyReport={id:number;technician_id:number;report_date:string;image_mime:string;created_at:string};
export function AssignmentManagerPanel(){const client=useQueryClient();const {data:technicians=[]}=useQuery({queryKey:["users"],queryFn:()=>api<Technician[]>("/users")});const [form,setForm]=useState({technician_id:"",task_number:"",subscription_number:"",task_type:"تقني",task_status:"عائق",city:"",notes:"",assigned_date:new Date().toISOString().slice(0,10)});const [message,setMessage]=useState("");async function submit(e:React.FormEvent){e.preventDefault();try{await api("/assignments",{method:"POST",body:JSON.stringify({...form,technician_id:Number(form.technician_id)})});setMessage("تم إسناد المهمة وإرسال إشعار للفني.");setForm({...form,technician_id:"",task_number:"",subscription_number:"",city:"",notes:""});client.invalidateQueries({queryKey:["assignments"]});}catch{setMessage("تعذر إسناد المهمة. تحقق من البيانات والصلاحيات.");}}return <div className="grid gap-5 xl:grid-cols-[1fr_1.4fr]"><form onSubmit={submit} className="panel"><h2 className="font-bold">إسناد مهمة</h2><div className="mt-4 grid gap-3"><select required value={form.technician_id} onChange={e=>setForm({...form,technician_id:e.target.value})} className="rounded-xl border bg-transparent p-3"><option value="">اختر الفني</option>{technicians.filter(user=>user.role==="technician").map(user=><option key={user.id} value={user.id}>{user.full_name}</option>)}</select><input required placeholder="رقم المهمة" value={form.task_number} onChange={e=>setForm({...form,task_number:e.target.value})} className="rounded-xl border bg-transparent p-3"/><input placeholder="رقم الاشتراك" value={form.subscription_number} onChange={e=>setForm({...form,subscription_number:e.target.value})} className="rounded-xl border bg-transparent p-3"/><input placeholder="المدينة" value={form.city} onChange={e=>setForm({...form,city:e.target.value})} className="rounded-xl border bg-transparent p-3"/><input type="date" value={form.assigned_date} onChange={e=>setForm({...form,assigned_date:e.target.value})} className="rounded-xl border bg-transparent p-3"/></div><button className="mt-4 w-full rounded-xl bg-brand p-3 font-semibold text-white">إسناد المهمة</button>{message&&<p className="mt-3 text-sm text-slate-500">{message}</p>}</form><AssignmentsPanel/></div>}
export function AssignmentsPanel(){const client=useQueryClient();const {data=[]}=useQuery({queryKey:["assignments"],queryFn:()=>api<Assignment[]>("/assignments")});async function complete(id:number){await api(`/assignments/${id}/complete`,{method:"POST"});client.invalidateQueries({queryKey:["assignments"]});}return <section className="panel overflow-x-auto"><h2 className="mb-4 font-bold">المهام المسندة</h2><table className="w-full text-right text-sm"><thead><tr className="text-slate-500"><th>المهمة</th><th>الاشتراك</th><th>النوع</th><th>التاريخ</th><th></th></tr></thead><tbody>{data.map(task=><tr className="border-t" key={task.id}><td className="py-3">{task.task_number}</td><td>{task.subscription_number}</td><td>{task.task_type}</td><td>{task.assigned_date}</td><td><button onClick={()=>complete(task.id)} className="rounded-lg bg-emerald-600 px-3 py-1.5 text-xs font-semibold text-white">إكمال</button></td></tr>)}</tbody></table>{!data.length&&<p className="py-8 text-center text-sm text-slate-500">لا توجد مهام مسندة حالياً.</p>}</section>}

export function DailyReportsPanel(){const {data=[],isLoading}=useQuery({queryKey:["daily-reports"],queryFn:()=>api<DailyReport[]>("/daily-reports")});return <section className="panel overflow-x-auto"><h2 className="mb-1 font-bold">التقارير اليومية</h2><p className="mb-4 text-sm text-slate-500">سجل الصور المرفوعة؛ لا يمكن عرض الصورة إلا عبر جلسة مصرح بها.</p><table className="w-full text-right text-sm"><thead><tr className="text-slate-500"><th>المعرف</th><th>الفني</th><th>تاريخ التقرير</th><th>النوع</th><th>وقت الرفع</th></tr></thead><tbody>{data.map(report=><tr className="border-t" key={report.id}><td className="py-3">#{report.id}</td><td>{report.technician_id}</td><td>{report.report_date}</td><td>{report.image_mime}</td><td>{new Date(report.created_at).toLocaleString("ar-SA")}</td></tr>)}</tbody></table>{isLoading?<p className="py-5 text-sm text-slate-500">جارٍ التحميل…</p>:!data.length?<p className="py-8 text-center text-sm text-slate-500">لا توجد تقارير حتى الآن.</p>:null}</section>}

export function ReportUploadPanel(){const [file,setFile]=useState<File>();const [date,setDate]=useState(new Date().toISOString().slice(0,10));const [result,setResult]=useState("");async function upload(){if(!file)return;const body=new FormData();body.append("image",file);const response=await fetch(`${process.env.NEXT_PUBLIC_API_URL??"http://localhost:8000/api/v1"}/daily-reports?report_date=${date}`,{method:"POST",headers:authHeaders(),body});setResult(response.ok?"تم حفظ التقرير بنجاح.":"تعذر حفظ التقرير. تأكد من الصورة وصلاحية الجلسة.");}return <section className="panel max-w-xl"><h2 className="font-bold">إضافة تقرير يومي</h2><p className="mt-1 text-sm text-slate-500">JPEG أو PNG، بحد أقصى 5 MB.</p><div className="mt-5 grid gap-3"><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="rounded-xl border bg-transparent p-3"/><input type="file" accept="image/jpeg,image/png" onChange={e=>setFile(e.target.files?.[0])} className="rounded-xl border bg-transparent p-3"/></div><button onClick={upload} disabled={!file} className="mt-4 rounded-xl bg-brand px-5 py-3 font-semibold text-white disabled:opacity-50">حفظ التقرير</button>{result&&<p className="mt-3 text-sm text-slate-600 dark:text-slate-300">{result}</p>}</section>}
