import { api } from "./api";

const taskKey = "fieldapp.pending_tasks";
type PendingTask = { id: string; payload: Record<string, unknown> };
const readTasks = (): PendingTask[] => { try { return JSON.parse(localStorage.getItem(taskKey) || "[]") as PendingTask[]; } catch { return []; } };
export function queueTask(payload: Record<string, unknown>, id = crypto.randomUUID()) { const tasks = readTasks(); if (!tasks.some(task => task.id === id)) tasks.push({ id, payload }); localStorage.setItem(taskKey, JSON.stringify(tasks)); }
export async function flushOfflineTasks() { const tasks = readTasks(); const remaining: PendingTask[] = []; for (const task of tasks) { try { await api("/tasks", { method: "POST", headers: { "Idempotency-Key": task.id }, body: JSON.stringify(task.payload) }); } catch (error) { if (error instanceof Error && "status" in error && [400, 401, 403, 422].includes(Number((error as { status?: number }).status))) continue; remaining.push(task); } } if (remaining.length) localStorage.setItem(taskKey, JSON.stringify(remaining)); else localStorage.removeItem(taskKey); }

const reportDb = "fieldapp-offline-reports";
export function queueReport(file: File, reportDate: string) { return new Promise<void>((resolve, reject) => { const request = indexedDB.open(reportDb, 1); request.onupgradeneeded = () => request.result.createObjectStore("reports", { keyPath: "id", autoIncrement: true }); request.onsuccess = () => { const transaction = request.result.transaction("reports", "readwrite"); transaction.objectStore("reports").add({ file, reportDate }); transaction.oncomplete = () => resolve(); transaction.onerror = () => reject(transaction.error); }; request.onerror = () => reject(request.error); }); }
export async function flushOfflineReports() { if (!navigator.onLine) return; const request = indexedDB.open(reportDb, 1); await new Promise<void>((resolve, reject) => { request.onupgradeneeded = () => request.result.createObjectStore("reports", { keyPath: "id", autoIncrement: true }); request.onsuccess = () => resolve(); request.onerror = () => reject(request.error); }); const db = request.result; const items = await new Promise<{ id: number; file: File; reportDate: string }[]>((resolve, reject) => { const transaction = db.transaction("reports", "readonly"); const get = transaction.objectStore("reports").getAll(); get.onsuccess = () => resolve(get.result); get.onerror = () => reject(get.error); }); for (const item of items) { const body = new FormData(); body.append("image", item.file); try { await api(`/daily-reports?report_date=${encodeURIComponent(item.reportDate)}`, { method: "POST", body }); const transaction = db.transaction("reports", "readwrite"); transaction.objectStore("reports").delete(item.id); } catch { break; } } }
